// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSubtitleFile(arg1, arg2) {
  return window['go']['main']['App']['AddSubtitleFile'](arg1, arg2);
}

export function ClearRecentFiles() {
  return window['go']['main']['App']['ClearRecentFiles']();
}

export function CloseTab(arg1) {
  return window['go']['main']['App']['CloseTab'](arg1);
}

export function CreateProfile(arg1, arg2) {
  return window['go']['main']['App']['CreateProfile'](arg1, arg2);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function FrameStep(arg1, arg2) {
  return window['go']['main']['App']['FrameStep'](arg1, arg2);
}

export function GetAllTabsState() {
  return window['go']['main']['App']['GetAllTabsState']();
}

export function GetAppDataDir() {
  return window['go']['main']['App']['GetAppDataDir']();
}

export function GetChangelog() {
  return window['go']['main']['App']['GetChangelog']();
}

export function GetMediaFilesInFolder(arg1) {
  return window['go']['main']['App']['GetMediaFilesInFolder'](arg1);
}

export function GetPlaybackInfo(arg1) {
  return window['go']['main']['App']['GetPlaybackInfo'](arg1);
}

export function GetPreferences() {
  return window['go']['main']['App']['GetPreferences']();
}

export function GetProfile() {
  return window['go']['main']['App']['GetProfile']();
}

export function GetProfileInfo() {
  return window['go']['main']['App']['GetProfileInfo']();
}

export function GetProfiles() {
  return window['go']['main']['App']['GetProfiles']();
}

export function GetRecentFiles() {
  return window['go']['main']['App']['GetRecentFiles']();
}

export function GetSeekThumbnailData(arg1) {
  return window['go']['main']['App']['GetSeekThumbnailData'](arg1);
}

export function GetSubtitleState(arg1) {
  return window['go']['main']['App']['GetSubtitleState'](arg1);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function LoadFile(arg1, arg2) {
  return window['go']['main']['App']['LoadFile'](arg1, arg2);
}

export function OpenFilePicker() {
  return window['go']['main']['App']['OpenFilePicker']();
}

export function OpenFilePickerMultiple() {
  return window['go']['main']['App']['OpenFilePickerMultiple']();
}

export function OpenFolderPicker() {
  return window['go']['main']['App']['OpenFolderPicker']();
}

export function OpenPlaylistVideo(arg1) {
  return window['go']['main']['App']['OpenPlaylistVideo'](arg1);
}

export function OpenProfile(arg1) {
  return window['go']['main']['App']['OpenProfile'](arg1);
}

export function OpenSubtitleFilePicker() {
  return window['go']['main']['App']['OpenSubtitleFilePicker']();
}

export function OpenVideo(arg1) {
  return window['go']['main']['App']['OpenVideo'](arg1);
}

export function RegenerateSeekThumbnails(arg1) {
  return window['go']['main']['App']['RegenerateSeekThumbnails'](arg1);
}

export function RenameProfile(arg1, arg2) {
  return window['go']['main']['App']['RenameProfile'](arg1, arg2);
}

export function ReorderProfiles(arg1) {
  return window['go']['main']['App']['ReorderProfiles'](arg1);
}

export function ResizeVideo() {
  return window['go']['main']['App']['ResizeVideo']();
}

export function SavePreferences(arg1) {
  return window['go']['main']['App']['SavePreferences'](arg1);
}

export function Seek(arg1, arg2) {
  return window['go']['main']['App']['Seek'](arg1, arg2);
}

export function SetPlaybackSpeed(arg1, arg2) {
  return window['go']['main']['App']['SetPlaybackSpeed'](arg1, arg2);
}

export function SetProfileColor(arg1, arg2) {
  return window['go']['main']['App']['SetProfileColor'](arg1, arg2);
}

export function SetSubtitleTrack(arg1, arg2) {
  return window['go']['main']['App']['SetSubtitleTrack'](arg1, arg2);
}

export function SetVideoFilter(arg1, arg2) {
  return window['go']['main']['App']['SetVideoFilter'](arg1, arg2);
}

export function SetVolume(arg1, arg2) {
  return window['go']['main']['App']['SetVolume'](arg1, arg2);
}

export function StartSeekThumbnailGeneration(arg1) {
  return window['go']['main']['App']['StartSeekThumbnailGeneration'](arg1);
}

export function SwitchTab(arg1) {
  return window['go']['main']['App']['SwitchTab'](arg1);
}

export function ToggleFullscreen() {
  return window['go']['main']['App']['ToggleFullscreen']();
}

export function TogglePlayback(arg1) {
  return window['go']['main']['App']['TogglePlayback'](arg1);
}
