// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {db} from '../models';
import {thumbs} from '../models';

export function ClearRecentFiles():Promise<void>;

export function CloseTab(arg1:string):Promise<void>;

export function GetAllTabsState():Promise<Record<string, boolean>>;

export function GetAppDataDir():Promise<string>;

export function GetChangelog():Promise<string>;

export function GetMediaFilesInFolder(arg1:string):Promise<Array<string>>;

export function GetPlaybackInfo(arg1:string):Promise<main.PlaybackInfo>;

export function GetPreferences():Promise<main.Preferences>;

export function GetRecentFiles():Promise<Array<db.RecentEntry>>;

export function GetSeekThumbnailData(arg1:string):Promise<thumbs.SeekThumbnailData>;

export function GetVersion():Promise<string>;

export function LoadFile(arg1:string,arg2:string):Promise<void>;

export function OpenFilePicker():Promise<string>;

export function OpenFilePickerMultiple():Promise<Array<string>>;

export function OpenFolderPicker():Promise<string>;

export function OpenPlaylistVideo(arg1:string):Promise<string>;

export function OpenVideo(arg1:string):Promise<string>;

export function RegenerateSeekThumbnails(arg1:string):Promise<void>;

export function ResizeVideo():Promise<void>;

export function SavePreferences(arg1:main.Preferences):Promise<void>;

export function Seek(arg1:string,arg2:number):Promise<void>;

export function SetVolume(arg1:string,arg2:number):Promise<void>;

export function StartSeekThumbnailGeneration(arg1:string):Promise<void>;

export function SwitchTab(arg1:string):Promise<void>;

export function ToggleFullscreen():Promise<void>;

export function TogglePlayback(arg1:string):Promise<void>;
