// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearRecentFiles():Promise<void>;

export function CloseTab(arg1:string):Promise<void>;

export function GetAllTabsState():Promise<Record<string, boolean>>;

export function GetAppDataDir():Promise<string>;

export function GetChangelog():Promise<string>;

export function GetPlaybackInfo(arg1:string):Promise<main.PlaybackInfo>;

export function GetRecentFiles():Promise<Array<main.RecentEntry>>;

export function GetVersion():Promise<string>;

export function OpenFilePicker():Promise<string>;

export function OpenVideo(arg1:string):Promise<string>;

export function Seek(arg1:string,arg2:number):Promise<void>;

export function SwitchTab(arg1:string):Promise<void>;

export function ToggleFullscreen():Promise<void>;

export function TogglePlayback(arg1:string):Promise<void>;
