// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearRecentFiles() {
  return window['go']['main']['App']['ClearRecentFiles']();
}

export function CloseTab(arg1) {
  return window['go']['main']['App']['CloseTab'](arg1);
}

export function GetAllTabsState() {
  return window['go']['main']['App']['GetAllTabsState']();
}

export function GetAppDataDir() {
  return window['go']['main']['App']['GetAppDataDir']();
}

export function GetChangelog() {
  return window['go']['main']['App']['GetChangelog']();
}

export function GetPlaybackInfo(arg1) {
  return window['go']['main']['App']['GetPlaybackInfo'](arg1);
}

export function GetRecentFiles() {
  return window['go']['main']['App']['GetRecentFiles']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function OpenFilePicker() {
  return window['go']['main']['App']['OpenFilePicker']();
}

export function OpenVideo(arg1) {
  return window['go']['main']['App']['OpenVideo'](arg1);
}

export function Seek(arg1, arg2) {
  return window['go']['main']['App']['Seek'](arg1, arg2);
}

export function SwitchTab(arg1) {
  return window['go']['main']['App']['SwitchTab'](arg1);
}

export function ToggleFullscreen() {
  return window['go']['main']['App']['ToggleFullscreen']();
}

export function TogglePlayback(arg1) {
  return window['go']['main']['App']['TogglePlayback'](arg1);
}
